Create finished books list
23nith/BookList-FE pull request #4
Opened 2022-09-06 05:36 UTC by 23nith

2022-09-06 07:27 UTC, normancapule commented
Please add proper descriptions to your PR. Screenshots, or GIFs of it working would help a lot

2022-09-06 07:33 UTC, normancapule reviewed
Looks good. Would be great if you can add a screenshot or gif of it working.

2022-09-06 07:33 UTC, normancapule commented on contexts/FinishedBooksContext.tsx
> +function FinishedBooksProvider(props) {
please convert to anonymous functions

```suggestion
const FinishedBooksProvider = (props) => {

```

2022-09-06 07:33 UTC, normancapule commented on contexts/FinishedBooksContext.tsx
> +export default FinishedBooksProvider;
Please reduce amount of times that you need to do `export default`. For next.js pages it's fine (since it is by design), but for regular components, please do a simple `export`. It's easier to autocomplete if it's using regular export

```suggestion
export { FinishedBooksProvider };
```

2022-09-06 07:33 UTC, normancapule commented on contexts/FinishedBooksContext.tsx
> +  const [finishedBooks, setFinishedBooks] = useState([]);
Consider adding additional stuff:
- isLoading state
- error state to capture errors from API. You can use this to display errors in the UI.

2022-09-06 07:33 UTC, normancapule commented on contexts/FinishedBooksContext.tsx
> +        Authorization: localStorage.getItem("token"),
Move this to the `api` folder. Contexts shouldn't care about API calls.

2022-09-06 07:33 UTC, normancapule commented on pages/finished.tsx
> +      console.log("blank");
Don't forget to delete console.log

2022-09-06 07:33 UTC, normancapule commented on pages/finished.tsx
> +  const { finishedBooks, setFinishedBooks, fetchFinishedBooks } =
`isLoading` or something similar should go here.

2022-09-06 07:33 UTC, normancapule commented on pages/finished.tsx
> +      {!finishedBooks && (
Add a `spinner` or `loading` section if `isLoading` is true

2022-09-06 07:33 UTC, normancapule commented on pages/_app.tsx
> +        <Component {...pageProps} />
Should a `/` page have its own layout?

2022-09-06 08:54 UTC, 23nith commented on pages/_app.tsx
> +        <Component {...pageProps} />
Hi, this is to exclude the navbar and top menu bar from appearing on the login screen.

2022-09-07 05:54 UTC, mikodagatan commented on pages/finished.tsx
> +      console.log("blank");
My bad for ignoring things like this. For sure sa project wag sana ipa-stay yung console.log pero I was a bit lenient when it comes to this

2022-09-13 01:15 UTC, normancapule requested changes
Almost there!

2022-09-13 01:15 UTC, normancapule commented on pages/finished.tsx
> +  useEffect(() => {}, [finishedBooks]);
What's this for?

2022-09-13 01:15 UTC, normancapule commented on api/finished_books.ts
> +  setFinishedBooks: Array<IListItem>;
Is this the correct type? Shouldn't this be a dispatch type since you are passing a useState function?

2022-09-13 01:15 UTC, normancapule commented on api/finished_books.ts
> +  setFinishedBooks: Array<IListItem>;
`nit`


```suggestion
  setFinishedBooks: IListItem[];

```

2022-09-13 01:15 UTC, normancapule commented on api/finished_books.ts
> +}: IFinishedBooksProps) => {
```suggestion
}: IFinishedBooksProps): Promise<IListItem[]> => {

```

Can you try this return function type, so that it'll be easier to map out the contents of a successful promise.

2022-09-13 01:15 UTC, normancapule commented on api/finished_books.ts
> +  })
We can make this better.
1. Create a shared function that returns the `Authorization`. 
```
const authHeaders = () => {
  const authKey = localStorage.getItem("token")
  return {
      "Content-Type": "application/json",
      Authorization: authKey  }
}
```
2. Create a function that returns the `baseUrl` that makes use of environment variables https://nextjs.org/docs/basic-features/environment-variables
```
const baseUrl = () => {
  return process.env.NEXT_PUBLIC_API_PATH
}
```

Store these 2 functions in a new file in api folder. Maybe called `base.ts`

With the above suggestions, this can be dryed up to:

```
fetch(`${baseUrl}/api/v1/finished_books`, {
  method: "get",
  headers: { ...authHeaders() }
}
```

This should also dry up your other api functions

2022-09-13 01:15 UTC, normancapule commented on contexts/FinishedBooksContext.tsx
> +  const [finishedBooks, setFinishedBooks] = useState([]);
As suggested yesterday, your `loading state` should be the responsibility of the provider. Where is `setIsLoading` here?

2022-09-13 01:15 UTC, normancapule commented on contexts/FinishedBooksContext.tsx
> +  const [finishedBooks, setFinishedBooks] = useState([]);
Did you test this component locally? I think this will return an error - `setIsLoading` not found

2022-09-13 01:17 UTC, normancapule commented on Interfaces/interfaces.tsx
> +export interface IListItem {
Why is there a folder called `Interfaces` with a file also called `interfaces` inside? Is this for api? If so - please move to `api/types.ts` folder.

Also - if the `ListItem` type is controlled by the backend, then please prefer a `type` instead of an `interface`. I recommend using `type` for any API-related types, then `interface` for types that developers control (props)

2022-09-13 05:39 UTC, mikodagatan commented on Interfaces/interfaces.tsx
> +export interface IListItem {
Yeah it's my bad when I suggested this, wherein in my previous company, we're just using `interface` all the way.

2022-09-13 15:07 UTC, 23nith commented on contexts/FinishedBooksContext.tsx
> +  const [finishedBooks, setFinishedBooks] = useState([]);
Hi, I would only be mainly using isLoading as argument for fetchFinishedBooks, that said, whenever I try to use fetchFinishedBooksList to generate a default value for finishedBooks it would always return an error since I am passing the setFinishedBooks (setState) as an argument for fetchFinishedBooksList. 

Like so:

`const [finishedBooks, setFinishedBooks] = useState(()=> {fetchFinishedBooks({isLoading, setFinishedBooks})};`

I couldn't figure out how to return the data outside of fetch without using setState. But good thing It turns out I only have to wrap the arguments w/in curly brackets the same way I have defined the Interface of the parameters to get rid of the error, it was an oversite on my part.

2022-09-13 15:11 UTC, 23nith commented on pages/finished.tsx
> +  useEffect(() => {}, [finishedBooks]);
I don't know why I've left it there :laughing:. I'll get rid of this.

2022-09-14 06:41 UTC, mikodagatan commented on contexts/FinishedBooksContext.tsx
> +  const [finishedBooks, setFinishedBooks] = useState([]);
@23nith for @normancapule's approval.

2022-09-14 08:49 UTC, normancapule commented on contexts/FinishedBooksContext.tsx
> +const FinishedBooksProvider = (props) => {
Please add an interface here. What are the expected props types?

2022-09-14 08:52 UTC, normancapule commented on contexts/FinishedBooksContext.tsx
> +export const FinishedBooks = createContext();
Please add a type for the expected structure of your book context. Since it looks like the value below can be finishedBooks or setFinishedBooks, 

```
export interface FinishedBooksContext {
  finishedBooks?: FinishedBooks[] (or was it booktype?)
  setFinishedBooks?: React.Dispatch<React.SetStateAction<FinishedBooks[]>>
}

export const FinishedBooks = createContext<FinishedBooksContext>({});

const FinishedBooksProvider = (props) => {
  const [finishedBooks, setFinishedBooks] = useState<FinishedBooks[]>([]);
```

2022-09-14 08:54 UTC, normancapule commented on api/finished_books.ts
> +  console.log("path: ", process.env.NEXT_PUBLIC_API_PATH);
Don't forget to remove console.log

2022-09-14 08:54 UTC, normancapule approved these changes
Looks good. Just check my comment about typing - other than that - niceee

2022-09-14 09:46 UTC, merged