Create modal component
23nith/BookList-FE pull request #6
Opened 2022-09-06 19:11 UTC by 23nith

2022-09-07 06:07 UTC, mikodagatan commented on components/Modal.tsx
> +const ModalContext = createContext();
Would be better to move this into a shared `contexts` folder, then place the context into `_app.tsx` in order to show that this is being applied globally.

2022-09-07 06:10 UTC, mikodagatan commented on pages/index.tsx
> +const Button = tw.button`py-10px px-15px border-0 leading-none rounded-3`;
Please move styles to `pages/index/styles.ts`

and move the file to `pages/index/index.tsx`  

We can organize our files better by putting them in one folder while trying to enact the `Single Responsibility Principle`

2022-09-07 06:15 UTC, mikodagatan commented on components/Modal.tsx
> +      onDismiss={() => {
you can create a `handleClickDismiss` function in order to make this cleaner.

```
const handleClickDismiss = () => setIsOpen(false);

onDismiss={handleClickDismiss}
```

2022-09-07 06:21 UTC, mikodagatan commented on pages/index.tsx
> +  <div className="closeFormDiv">
Will wait for a PR on using TailwindCSS styled components to change this.

2022-09-07 06:22 UTC, mikodagatan commented on pages/index.tsx
> +const Button = tw.button`py-10px px-15px border-0 leading-none rounded-3`;
for `px-15px` there's really no need to apply this in the tailwind config file, you can just use `px-[15px]` instead.

2022-09-07 06:23 UTC, mikodagatan commented on pages/index.tsx
> +const LoginForm = ({ onSubmit, submitButton }) => {
use `interface` props please

2022-09-07 06:24 UTC, mikodagatan commented on components/Modal.tsx
> +const ModalContext = createContext();
Can't really articulate my mind on how to do this better, I'll leave this to @Normz's discretion.

2022-09-07 06:25 UTC, 23nith commented on components/Modal.tsx
> +const ModalContext = createContext();
Hi, the modal context need only to be accessible to the ModalOpenButton and ModalContents since I intended this to be a compound component. Thanks!

2022-09-07 06:25 UTC, mikodagatan commented on components/Modal.tsx
> +const ModalDismissButton = ({ children: child }) => {
use `interface` props please

2022-09-07 10:25 UTC, normancapule requested changes
Not nearly there. Please check our comments thank you!

2022-09-07 10:25 UTC, normancapule commented on pages/styled.tsx
> +import tw from "tailwind-styled-components";
Anyting you put in the `pages` folder will be treated as a page component. I recommend moving this to the component folder

2022-09-07 10:25 UTC, normancapule commented on components/Modal.tsx
> +const Modal = (props) => {
What is the type of props?

2022-09-07 10:32 UTC, mikodagatan commented on pages/index.tsx
> +          <Modal>
After re-reading this many times, I think this is just doing the same thing as before with additional `context`s to it. We're just renaming them up. In the end there are still 2 modals that are created instead.

There are some of the [concepts I want you to try out here](https://hesambayat.com/how-to-create-dialog-boxes-with-react-hook-and-react-context/). We're trying to make the modal dynamic and we're using the `ContextAPI` to improve it. No need to follow this to the core, but the concept being introduced here will help you out!

2022-09-07 10:45 UTC, normancapule commented on pages/index.tsx
> +          <Modal>
Contexts are useful for global use cases. E.g. in what @mikodagatan linked above, there is a modal that is used by multiple pages and can be triggered in more than 1 place. 

But with your modal - its only for 1 page - Login / Registration. And this modal has trigger buttons that are also in the same page, next to each other (screenshot of your PR would help us visualize)

What I would suggest:

1. Remove the context. This is an overkill solution to a simple use case.
2. Bring back your old implementation. It's already correct. Make use of states.

```
  const [isModalOpan, setIsModalOpen] = useState(false);
  const [modalView, setModalView] = useState<undefined | "login" | "register">();
```

Then you would have a function that handles closing and opening the modal:

```
const handleModalOpen = (modalView: "login" | "register") => {
  setIsModalOpen(true)
  setModalView(modalView)
}
```

```
const handleModalClose = () => {
  setIsModalOpen(false)
}
```

Your buttons would have a `handleClick` attribute that accepts the `handleModalOpen` function.

```
<button onClick={() => handleModalOpen("login")>Login</button>
<button onClick={() => handleModalOpen("register")>Regsiter</button>
```

Lastly, your modal will accept the `handleModalClose ` because iirc it can be closed if you click a `cancel` button or the `x` button in the modal. 

```
<Dialog isOpen={isModalOpan} onDismiss={handleModalClose }>
  {modalView === "login" && <LoginForm />}
  {modalView === "register" && <RegisterForm />}
</Dialog>
```

2022-09-07 10:59 UTC, mikodagatan commented on pages/index.tsx
> +          <Modal>
Hmm, he's right. Like @normancapule said, his proposed solution is best if you're not gonna make modals in other pages. It's good also for simplicity's sake. And, you can opt to not make more modals to circumvent this.

The idea of using the global context to crea e online dynamic modal is better once you're using it on many pages.

So it's my bad for wrongly assuming you're gonna use this more beyond the log in page. Sorry.

2022-09-07 12:13 UTC, 23nith commented on pages/index.tsx
> +          <Modal>
Hi, I have a noob question sorry.. Should I ought to avoid using compound components moving forward then? If so, when is it ideal to implement it?

2022-09-08 00:08 UTC, 23nith commented on pages/index.tsx
> +          <Modal>
> After re-reading this many times, I think this is just doing the same thing as before with additional `context`s to it. We're just renaming them up. In the end there are still 2 modals that are created instead.
> 

I just want to clarify why this is not considered dynamic.. Highlighted portion shows the dynamic contents (LoginForm component included is also dynamic). The underlined part is the button that would trigger the modal w/c is also dynamic. (pictured below)

![modal question](https://user-images.githubusercontent.com/30313350/189005768-229b9b52-85ec-491d-8f21-ac5b3066f37e.PNG)

> There are some of the [concepts I want you to try out here](https://hesambayat.com/how-to-create-dialog-boxes-with-react-hook-and-react-context/). We're trying to make the modal dynamic and we're using the `ContextAPI` to improve it. No need to follow this to the core, but the concept being introduced here will help you out!

I've checked the link provided, it appears to be also a compound component.. w/c uses context to share states between its member components. The only difference is that the dismiss button (triggering the unSetModal) is less dynamic and is defined within the Modal component. I just want to clarify since I am new to this.

2022-09-08 01:07 UTC, normancapule commented on pages/index.tsx
> +          <Modal>
@23nith 

> Should I avoid using compound components moving forward then? 

For this specific scenario, I don't see a point of using a compound component since:
- the modal is only being used in 1 page.
- the trigger points of the modal are in the same page - and are just 2 buttons.

So in my mind, the complexity of converting this to a compound component is not worth it.

A good scenario when to use compound component - UserProvider. Like the example I mentioned here https://sourcepad.slack.com/archives/C03RHA8F36K/p1662374301849309

Why is it a good scenario?
- We would have "authorized" pages. These should not be accessible if the `user` is nil. Which `UserProvider` provides
- The `user` state will be exposed to all children components. Meaning this can be used in various places (Navbar avatar, Dashboard greeting ("Hello there {user name}")

2022-09-08 01:16 UTC, 23nith commented on pages/index.tsx
> +          <Modal>
I see. I'll take note of this. Thank you so much for clarifying! :smiley:

2022-09-08 02:18 UTC, 23nith commented on pages/index.tsx
> +          <Modal>
> There are some of the [concepts I want you to try out here](https://hesambayat.com/how-to-create-dialog-boxes-with-react-hook-and-react-context/). We're trying to make the modal dynamic and we're using the `ContextAPI` to improve it. No need to follow this to the core, but the concept being introduced here will help you out!

I created a new modal using react-hook and react-context as was suggested, but for some reason I cannot get the spinner feature inside the Loginform component to work

I made this on a new branch for testing purposes, can I make a new PR for this branch just so I could let you check it?

I left the previous modal I made with a working spinner for comparison 

![image](https://user-images.githubusercontent.com/30313350/189016867-5329598d-3c4e-450f-9af3-f7e38734ec34.png)

![image](https://user-images.githubusercontent.com/30313350/189016993-1928916c-19f6-4488-867e-74bc54385e79.png)

2022-09-08 02:23 UTC, normancapule commented on pages/index.tsx
> +          cloneElement(
Why are you using `cloneElement`?

2022-09-08 02:26 UTC, normancapule commented on pages/index.tsx
> +          <Modal>
Why are you storing an element in the state? This is firing off some alarm bells in my brain. 

Yes sure go ahead and create a PR about this. Make sure this PR is that PR's parent so that it is easier to read.

Alternatively - we can pair on this. I wanna make sure I understand where this is going

2022-09-08 02:31 UTC, 23nith commented on pages/index.tsx
> +          cloneElement(
I was passing a submit button as props.. cloneElement will add submit as the button's type.

2022-09-08 02:36 UTC, normancapule commented on pages/index.tsx
> +          cloneElement(
Why are you passing the whole submit button as a prop? 

Look - what is the difference between the login and register component submit button? Just the function that it triggers right? Why not - instead of this - you pass the submit function instead?

```
<LoginForm handleSubmit={loginSubmit} />
<RegisterForm handleSubmit={registerSubmit} />
```

2022-09-08 02:37 UTC, normancapule commented on pages/index.tsx
> +const LoginForm = ({ onSubmit, submitButton, isLoading }: LoginFormProps) => {
Please move the LoginForm to a separate component. The page component is already becoming too big.

2022-09-08 04:46 UTC, mikodagatan commented on pages/index.tsx
> +          <Modal>
Sorry @normancapule the article I shared included it.

@23nith can you try checking this out? Try applying the idea from the photo below instead of storing objects on the state. 

It's coming from this article, which also shares why it's not a good idea. 

https://stackoverflow.com/questions/66919014/is-it-a-good-idea-to-store-components-in-state

![Screenshot_2022-09-08-12-40-55-931_com android chrome](https://user-images.githubusercontent.com/22701608/189036023-1d9c2ee5-0046-486f-b0f2-910146080a7f.jpg)

2022-09-08 05:03 UTC, 23nith commented on pages/index.tsx
> +          <Modal>
> Why are you storing an element in the state? This is firing off some alarm bells in my brain.
> 
> Yes sure go ahead and create a PR about this. Make sure this PR is that PR's parent so that it is easier to read.

Hi @normancapule @mikodagatan here is the link to the testing code which I placed in a new PR https://github.com/23nith/BookList-FE/pull/7

> 
> Alternatively - we can pair on this. I wanna make sure I understand where this is going
Yes sure, that would be great

2022-09-08 05:05 UTC, 23nith commented on pages/index.tsx
> +          <Modal>
> @23nith can you try checking this out? Try applying the idea from the photo below instead of storing objects on the state.
> 

Alright, checking this right now...

2022-09-08 05:19 UTC, 23nith commented on pages/index.tsx
> +          cloneElement(
Because the modal was intended to be dynamic down to the style of the submit buttons..

2022-09-08 05:23 UTC, normancapule commented on pages/index.tsx
> +          cloneElement(
It can still be dynamic even with it being contained in 2 components (like what I posted above). 

LoginForm will have a specific style for the submit button
RegisterForm will have a specific style for the submit button

The only difference between the 2 would be the submit function prop.

Cloning the submit button seems like overcomplicating it vs. just having each component its own submit button. And have each component control the style of that button.

2022-09-08 05:23 UTC, 23nith commented on pages/index.tsx
> +          cloneElement(
> Why are you passing the whole submit button as a prop?
> 
> Look - what is the difference between the login and register component submit button? Just the function that it triggers right? 

Because the modal was intended to be dynamic down to the style of the submit buttons..  LoginForm renders the whole form including the type of button that it would render including the styles.

> Why not - instead of this - you pass the submit function instead?

Okay, will try to do this

2022-09-13 01:24 UTC, normancapule commented on api/login.tsx
> +  fetch("http://localhost:3000/login", {
See my comment about drying up the baseUrl and headers here - https://github.com/23nith/BookList-FE/pull/4/files#r969052691

2022-09-13 01:24 UTC, normancapule commented on package-lock.json
>          "eslint": "8.22.0",
As discussed yesterday - after merging the PRs please pick one: `package-lock.json` or `yarn.lock`. Yarn already warned you to not keep 2 package managers in 1 project

2022-09-13 01:24 UTC, normancapule commented on components/styled.tsx
> +};
`nit`

Move this inside your component. The `styled` folders should only hold styles.

2022-09-13 01:24 UTC, normancapule commented on components/LoginForm.tsx
> +        <input
This and `password` are required fields right? Are you validating these correctly? Can the submit button be pressed even if username and password are empty fields?

2022-09-13 01:24 UTC, normancapule commented on api/register.tsx
> +  console.log("register", formData);
console.log

2022-09-13 01:24 UTC, normancapule commented on api/login.tsx
> +      localStorage.setItem("token", res.headers.get("Authorization"));
If this is successful, is the user redirected automatically to a "logged in" page?

2022-09-13 01:24 UTC, normancapule commented
Don't forget to fill up your PRs with a meaningful description. Screenshot and gifs would go along way helping us review your PR faster.

2022-09-13 07:04 UTC, 23nith commented on api/login.tsx
> +      localStorage.setItem("token", res.headers.get("Authorization"));
This is what I was trying to figure out during the weekend. Because I used to get away with using useRoute() inside my fetch requests, but after moving the fetch request on a separate file under API, I can no longer use useRoute() since it is outside of a component. I saw your implementation on your template that you sent us, and I think will try to replicate it. I will also make a session context to handle routing just like what you did. Thank by the way for sending us your template :smile:

2022-09-13 09:31 UTC, normancapule commented on api/login.tsx
> +      localStorage.setItem("token", res.headers.get("Authorization"));
There's another way to do this - make the function accept an optional `onCompleted` function. 

So in Line 15, you would have something like

`onCompleted && onCompleted(res)`

So if you call the `login` function in a component, you can code it like this:

```
const onCompleted = () => {
  // redirect logic
}

await login(onCompleted)
```

I leave this up to you. Don't need to be as complicated as the template.

2022-09-13 10:36 UTC, 23nith commented on api/login.tsx
> +      localStorage.setItem("token", res.headers.get("Authorization"));
:open_mouth: okay, will try to do this, thanks!

2022-09-13 20:55 UTC, 23nith commented on api/login.tsx
> +      localStorage.setItem("token", res.headers.get("Authorization"));
It worked!! Thanks again !! :smile:

2022-09-14 06:45 UTC, mikodagatan commented on api/finished_books.ts
> +export const fetchFinishedBooks = ({
Where are you calling this now that it's not in the context?

2022-09-14 06:53 UTC, 23nith commented on api/finished_books.ts
> +export const fetchFinishedBooks = ({
Hi, I forgot to remove this. It came along with the changes made when I git cherry-picked the commit from create_finished_books_list branch to dry up the api.

2022-09-14 08:27 UTC, mikodagatan commented on api/finished_books.ts
> +export const fetchFinishedBooks = ({
I think this is more important though, `fetchFinishedBooks` has to be in `api`. What are you using in its stead if we're gonna delete this?

2022-09-14 08:30 UTC, 23nith commented on api/finished_books.ts
> +export const fetchFinishedBooks = ({
It's already in the api folder.

2022-09-14 08:35 UTC, mikodagatan commented on api/finished_books.ts
> +export const fetchFinishedBooks = ({
Thanks for the clarification @23nith

2022-09-14 08:35 UTC, mikodagatan approved these changes
Looks good to me

2022-09-14 08:44 UTC, merged