Add style to mainpage
23nith/BookList-FE pull request #8
Opened 2022-09-08 14:05 UTC by 23nith

2022-09-14 13:59 UTC, 23nith commented
I will do the styling of the top menu bar on a separate PR. I will branch it from the current develop branch.

![chrome_MPxzh718YT](https://user-images.githubusercontent.com/30313350/190174725-836bd8c9-14d0-4643-b366-8583d4c7b01d.gif)

2022-09-14 14:11 UTC, mikodagatan commented on components/BookList.tsx
> +import styles from "../styles/Home.module.css";
Hope that you'd get to apply the `tailwindcss-styled-components` instead of module.css

Will still approve despite this for the sake of time.

2022-09-14 14:14 UTC, mikodagatan commented on pages/discover.tsx
> +          books.map((book) => <BookList book={book} state={"discover"} />)}
Please add a key for `BookList`
```
<BookList key={book.id} book={book} state={"discover"} />
```

2022-09-14 14:14 UTC, mikodagatan commented on pages/finished.tsx
> +          <BookList book={listItem.book} state={"finished"} />
Please add a `key`

2022-09-14 14:14 UTC, mikodagatan commented on pages/list.tsx
> +          <BookList book={list.book} state={"reading"} />
Please add `key`

2022-09-14 14:15 UTC, mikodagatan commented on styles/globals.css
> +  color: rgba(67, 68, 73, 1);
Better put the specific color in tailwindcss config file.

2022-09-14 14:16 UTC, mikodagatan commented on styles/globals.css
> +  min-height: 270px;
`min-h-[270px]`

2022-09-14 14:20 UTC, mikodagatan commented on styles/globals.css
> +  grid-template-columns: 140px 1fr;
https://tailwindcss.com/docs/grid-template-columns#arbitrary-values

```
 grid-cols-[140px_1fr]
```

2022-09-14 14:21 UTC, mikodagatan commented on styles/globals.css
> +  flex-grow: 2;
https://tailwindcss.com/docs/flex-grow#arbitrary-values

```
 grow-[2]
```

2022-09-14 14:22 UTC, mikodagatan commented on components/BookList.tsx
> +      <div className="grow-3 p-5 max-h-[255px] text-ellipsis overflow-hidden">
`grow-[3]`

it doesn't seem like `grow-3` is in the documentation.

2022-09-14 14:22 UTC, mikodagatan commented on components/BookList.tsx
> +          <div className="">
remove `className=""`

2022-09-14 14:42 UTC, mikodagatan commented on components/BookList.tsx
> +    console.log("clicked");
remove console.log

2022-09-14 14:43 UTC, mikodagatan commented on styles/Home.module.css
> +/* .booklist_box {
`.booklist_box` was referenced, is this gonna stay as a comment?

2022-09-14 14:44 UTC, mikodagatan commented on styles/Home.module.css
> +/* .nav_li_active {
Please remove the comment.

2022-09-14 14:44 UTC, mikodagatan requested changes
Looks good to me. Just a few comments.

2022-09-15 09:22 UTC, mikodagatan approved these changes
Looks good to mr

2022-09-15 09:23 UTC, merged